### ISSUE TITLE
Storing training samples from previous iterations?

### ISSUE THREAD

**Issue by HelgiHelgason** [balajiln/mondrianforest#8]
Great project, have been looking at possibilities to modify this code to support streaming learning on the fly. One question I have has to do with what happens to training examples from previous iterations:

It seems that after _mf.fit()_ is run and _mf.partial_fit()_ is called, the nodes are still holding references (indicies) to previous training samples:

_self.train_ids[node_id] = np.append(self.train_ids[node_id], train_ids_new)_

in the method _add_training_points_to_node_

When I try to replace (rather than concatenate) _data["x_train"]_ with new training samples, I get an error in _get_data_min_max(data, train_ids)_ which is caused by _train_ids_ being empty.

**Comment by balajiln** [comment]
The reason I stored train_ids is due to "pausing" --- see section 5.5.1 of my [thesis](http://www.gatsby.ucl.ac.uk/~balaji/balaji-phd-thesis.pdf) for slightly better explanation than the NIPS paper. In a nutshell, the issue is controlling the complexity of online decision trees; if you set "min_samples_split", then you need to keep around data points if number of data points in leaf node becomes greater than min_samples_split. 

You can set max_depth alternately; this is the lambda parameter. If you can set lambda, you don't need to keep around data points. I didn't have a clean solution for setting lambda in the streaming setting, hence the current code does not support that. If you have a way to set lambda, you can disable pausing/unpausing in the code which would get rid of this issue.

Hope that helps!
